language: python
sudo: false

python:
  - 3.5

git:
  depth: 5

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - mkdocs build -c

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    local_dir: site
    skip_cleanup: true
    on:
      repo: ldez/regex-memo
